// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AlertRuleGroupMetadata alert rule group metadata
//
// swagger:model AlertRuleGroupMetadata
type AlertRuleGroupMetadata struct {

	// interval
	Interval int64 `json:"interval,omitempty"`
}

// Validate validates this alert rule group metadata
func (m *AlertRuleGroupMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this alert rule group metadata based on context it is used
func (m *AlertRuleGroupMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AlertRuleGroupMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AlertRuleGroupMetadata) UnmarshalBinary(b []byte) error {
	var res AlertRuleGroupMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
