// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// QueryHistoryMigrationResponse query history migration response
//
// swagger:model QueryHistoryMigrationResponse
type QueryHistoryMigrationResponse struct {

	// message
	Message string `json:"message,omitempty"`

	// starred count
	StarredCount int64 `json:"starredCount,omitempty"`

	// total count
	TotalCount int64 `json:"totalCount,omitempty"`
}

// Validate validates this query history migration response
func (m *QueryHistoryMigrationResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this query history migration response based on context it is used
func (m *QueryHistoryMigrationResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *QueryHistoryMigrationResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QueryHistoryMigrationResponse) UnmarshalBinary(b []byte) error {
	var res QueryHistoryMigrationResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
