// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// QueryToMigrate query to migrate
//
// swagger:model QueryToMigrate
type QueryToMigrate struct {

	// comment
	Comment string `json:"comment,omitempty"`

	// created at
	CreatedAt int64 `json:"createdAt,omitempty"`

	// datasource Uid
	DatasourceUID string `json:"datasourceUid,omitempty"`

	// queries
	Queries JSON `json:"queries,omitempty"`

	// starred
	Starred bool `json:"starred,omitempty"`
}

// Validate validates this query to migrate
func (m *QueryToMigrate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this query to migrate based on context it is used
func (m *QueryToMigrate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *QueryToMigrate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QueryToMigrate) UnmarshalBinary(b []byte) error {
	var res QueryToMigrate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
