// Code generated by go-swagger; DO NOT EDIT.

package annotations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-api-golang-client/goclient/models"
)

// PostAnnotationReader is a Reader for the PostAnnotation structure.
type PostAnnotationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAnnotationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAnnotationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAnnotationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAnnotationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostAnnotationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAnnotationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAnnotationOK creates a PostAnnotationOK with default headers values
func NewPostAnnotationOK() *PostAnnotationOK {
	return &PostAnnotationOK{}
}

/* PostAnnotationOK describes a response with status code 200, with default header values.

(empty)
*/
type PostAnnotationOK struct {
	Payload *models.PostAnnotationOKBody
}

func (o *PostAnnotationOK) Error() string {
	return fmt.Sprintf("[POST /annotations][%d] postAnnotationOK  %+v", 200, o.Payload)
}
func (o *PostAnnotationOK) GetPayload() *models.PostAnnotationOKBody {
	return o.Payload
}

func (o *PostAnnotationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostAnnotationOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAnnotationBadRequest creates a PostAnnotationBadRequest with default headers values
func NewPostAnnotationBadRequest() *PostAnnotationBadRequest {
	return &PostAnnotationBadRequest{}
}

/* PostAnnotationBadRequest describes a response with status code 400, with default header values.

BadRequestError is returned when the request is invalid and it cannot be processed.
*/
type PostAnnotationBadRequest struct {
	Payload *models.ErrorResponseBody
}

func (o *PostAnnotationBadRequest) Error() string {
	return fmt.Sprintf("[POST /annotations][%d] postAnnotationBadRequest  %+v", 400, o.Payload)
}
func (o *PostAnnotationBadRequest) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *PostAnnotationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAnnotationUnauthorized creates a PostAnnotationUnauthorized with default headers values
func NewPostAnnotationUnauthorized() *PostAnnotationUnauthorized {
	return &PostAnnotationUnauthorized{}
}

/* PostAnnotationUnauthorized describes a response with status code 401, with default header values.

UnauthorizedError is returned when the request is not authenticated.
*/
type PostAnnotationUnauthorized struct {
	Payload *models.ErrorResponseBody
}

func (o *PostAnnotationUnauthorized) Error() string {
	return fmt.Sprintf("[POST /annotations][%d] postAnnotationUnauthorized  %+v", 401, o.Payload)
}
func (o *PostAnnotationUnauthorized) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *PostAnnotationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAnnotationForbidden creates a PostAnnotationForbidden with default headers values
func NewPostAnnotationForbidden() *PostAnnotationForbidden {
	return &PostAnnotationForbidden{}
}

/* PostAnnotationForbidden describes a response with status code 403, with default header values.

ForbiddenError is returned if the user/token has insufficient permissions to access the requested resource.
*/
type PostAnnotationForbidden struct {
	Payload *models.ErrorResponseBody
}

func (o *PostAnnotationForbidden) Error() string {
	return fmt.Sprintf("[POST /annotations][%d] postAnnotationForbidden  %+v", 403, o.Payload)
}
func (o *PostAnnotationForbidden) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *PostAnnotationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAnnotationInternalServerError creates a PostAnnotationInternalServerError with default headers values
func NewPostAnnotationInternalServerError() *PostAnnotationInternalServerError {
	return &PostAnnotationInternalServerError{}
}

/* PostAnnotationInternalServerError describes a response with status code 500, with default header values.

InternalServerError is a general error indicating something went wrong internally.
*/
type PostAnnotationInternalServerError struct {
	Payload *models.ErrorResponseBody
}

func (o *PostAnnotationInternalServerError) Error() string {
	return fmt.Sprintf("[POST /annotations][%d] postAnnotationInternalServerError  %+v", 500, o.Payload)
}
func (o *PostAnnotationInternalServerError) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *PostAnnotationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
