// Code generated by go-swagger; DO NOT EDIT.

package annotations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-api-golang-client/goclient/models"
)

// UpdateAnnotationReader is a Reader for the UpdateAnnotation structure.
type UpdateAnnotationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateAnnotationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateAnnotationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateAnnotationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUpdateAnnotationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateAnnotationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateAnnotationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateAnnotationOK creates a UpdateAnnotationOK with default headers values
func NewUpdateAnnotationOK() *UpdateAnnotationOK {
	return &UpdateAnnotationOK{}
}

/* UpdateAnnotationOK describes a response with status code 200, with default header values.

An OKResponse is returned if the request was successful.
*/
type UpdateAnnotationOK struct {
	Payload *models.SuccessResponseBody
}

func (o *UpdateAnnotationOK) Error() string {
	return fmt.Sprintf("[PUT /annotations/{annotation_id}][%d] updateAnnotationOK  %+v", 200, o.Payload)
}
func (o *UpdateAnnotationOK) GetPayload() *models.SuccessResponseBody {
	return o.Payload
}

func (o *UpdateAnnotationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateAnnotationBadRequest creates a UpdateAnnotationBadRequest with default headers values
func NewUpdateAnnotationBadRequest() *UpdateAnnotationBadRequest {
	return &UpdateAnnotationBadRequest{}
}

/* UpdateAnnotationBadRequest describes a response with status code 400, with default header values.

BadRequestError is returned when the request is invalid and it cannot be processed.
*/
type UpdateAnnotationBadRequest struct {
	Payload *models.ErrorResponseBody
}

func (o *UpdateAnnotationBadRequest) Error() string {
	return fmt.Sprintf("[PUT /annotations/{annotation_id}][%d] updateAnnotationBadRequest  %+v", 400, o.Payload)
}
func (o *UpdateAnnotationBadRequest) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *UpdateAnnotationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateAnnotationUnauthorized creates a UpdateAnnotationUnauthorized with default headers values
func NewUpdateAnnotationUnauthorized() *UpdateAnnotationUnauthorized {
	return &UpdateAnnotationUnauthorized{}
}

/* UpdateAnnotationUnauthorized describes a response with status code 401, with default header values.

UnauthorizedError is returned when the request is not authenticated.
*/
type UpdateAnnotationUnauthorized struct {
	Payload *models.ErrorResponseBody
}

func (o *UpdateAnnotationUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /annotations/{annotation_id}][%d] updateAnnotationUnauthorized  %+v", 401, o.Payload)
}
func (o *UpdateAnnotationUnauthorized) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *UpdateAnnotationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateAnnotationForbidden creates a UpdateAnnotationForbidden with default headers values
func NewUpdateAnnotationForbidden() *UpdateAnnotationForbidden {
	return &UpdateAnnotationForbidden{}
}

/* UpdateAnnotationForbidden describes a response with status code 403, with default header values.

ForbiddenError is returned if the user/token has insufficient permissions to access the requested resource.
*/
type UpdateAnnotationForbidden struct {
	Payload *models.ErrorResponseBody
}

func (o *UpdateAnnotationForbidden) Error() string {
	return fmt.Sprintf("[PUT /annotations/{annotation_id}][%d] updateAnnotationForbidden  %+v", 403, o.Payload)
}
func (o *UpdateAnnotationForbidden) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *UpdateAnnotationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateAnnotationInternalServerError creates a UpdateAnnotationInternalServerError with default headers values
func NewUpdateAnnotationInternalServerError() *UpdateAnnotationInternalServerError {
	return &UpdateAnnotationInternalServerError{}
}

/* UpdateAnnotationInternalServerError describes a response with status code 500, with default header values.

InternalServerError is a general error indicating something went wrong internally.
*/
type UpdateAnnotationInternalServerError struct {
	Payload *models.ErrorResponseBody
}

func (o *UpdateAnnotationInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /annotations/{annotation_id}][%d] updateAnnotationInternalServerError  %+v", 500, o.Payload)
}
func (o *UpdateAnnotationInternalServerError) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *UpdateAnnotationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
