version: '3'

networks:
  grafana-api-golang-client-test:
    driver: bridge

services:

  grafana-api-golang-client:
    image: golang:1.18
    environment:
      - GRAFANA_URL=http://grafana:3000
      - GRAFANA_AUTH=admin:admin
      - GRAFANA_ORG_ID=1
      - GRAFANA_VERSION
    working_dir: /go/src/github.com/grafana/grafana-api-golang-client
    volumes:
      - .:/go/src/github.com/grafana/grafana-api-golang-client
    depends_on:
      - grafana
    networks:
      - grafana-api-golang-client-test

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    networks:
      - grafana-api-golang-client-test
