// Code generated by go-swagger; DO NOT EDIT.

package provisioning

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRouteGetTemplateParams creates a new RouteGetTemplateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRouteGetTemplateParams() *RouteGetTemplateParams {
	return &RouteGetTemplateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRouteGetTemplateParamsWithTimeout creates a new RouteGetTemplateParams object
// with the ability to set a timeout on a request.
func NewRouteGetTemplateParamsWithTimeout(timeout time.Duration) *RouteGetTemplateParams {
	return &RouteGetTemplateParams{
		timeout: timeout,
	}
}

// NewRouteGetTemplateParamsWithContext creates a new RouteGetTemplateParams object
// with the ability to set a context for a request.
func NewRouteGetTemplateParamsWithContext(ctx context.Context) *RouteGetTemplateParams {
	return &RouteGetTemplateParams{
		Context: ctx,
	}
}

// NewRouteGetTemplateParamsWithHTTPClient creates a new RouteGetTemplateParams object
// with the ability to set a custom HTTPClient for a request.
func NewRouteGetTemplateParamsWithHTTPClient(client *http.Client) *RouteGetTemplateParams {
	return &RouteGetTemplateParams{
		HTTPClient: client,
	}
}

/* RouteGetTemplateParams contains all the parameters to send to the API endpoint
   for the route get template operation.

   Typically these are written to a http.Request.
*/
type RouteGetTemplateParams struct {

	/* Name.

	   Template Name
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the route get template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteGetTemplateParams) WithDefaults() *RouteGetTemplateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the route get template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteGetTemplateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the route get template params
func (o *RouteGetTemplateParams) WithTimeout(timeout time.Duration) *RouteGetTemplateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the route get template params
func (o *RouteGetTemplateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the route get template params
func (o *RouteGetTemplateParams) WithContext(ctx context.Context) *RouteGetTemplateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the route get template params
func (o *RouteGetTemplateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the route get template params
func (o *RouteGetTemplateParams) WithHTTPClient(client *http.Client) *RouteGetTemplateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the route get template params
func (o *RouteGetTemplateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the route get template params
func (o *RouteGetTemplateParams) WithName(name string) *RouteGetTemplateParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the route get template params
func (o *RouteGetTemplateParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *RouteGetTemplateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
