// Code generated by go-swagger; DO NOT EDIT.

package provisioning

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRouteDeleteContactpointsParams creates a new RouteDeleteContactpointsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRouteDeleteContactpointsParams() *RouteDeleteContactpointsParams {
	return &RouteDeleteContactpointsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRouteDeleteContactpointsParamsWithTimeout creates a new RouteDeleteContactpointsParams object
// with the ability to set a timeout on a request.
func NewRouteDeleteContactpointsParamsWithTimeout(timeout time.Duration) *RouteDeleteContactpointsParams {
	return &RouteDeleteContactpointsParams{
		timeout: timeout,
	}
}

// NewRouteDeleteContactpointsParamsWithContext creates a new RouteDeleteContactpointsParams object
// with the ability to set a context for a request.
func NewRouteDeleteContactpointsParamsWithContext(ctx context.Context) *RouteDeleteContactpointsParams {
	return &RouteDeleteContactpointsParams{
		Context: ctx,
	}
}

// NewRouteDeleteContactpointsParamsWithHTTPClient creates a new RouteDeleteContactpointsParams object
// with the ability to set a custom HTTPClient for a request.
func NewRouteDeleteContactpointsParamsWithHTTPClient(client *http.Client) *RouteDeleteContactpointsParams {
	return &RouteDeleteContactpointsParams{
		HTTPClient: client,
	}
}

/* RouteDeleteContactpointsParams contains all the parameters to send to the API endpoint
   for the route delete contactpoints operation.

   Typically these are written to a http.Request.
*/
type RouteDeleteContactpointsParams struct {

	/* UID.

	   UID is the contact point unique identifier
	*/
	UID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the route delete contactpoints params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteDeleteContactpointsParams) WithDefaults() *RouteDeleteContactpointsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the route delete contactpoints params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteDeleteContactpointsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the route delete contactpoints params
func (o *RouteDeleteContactpointsParams) WithTimeout(timeout time.Duration) *RouteDeleteContactpointsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the route delete contactpoints params
func (o *RouteDeleteContactpointsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the route delete contactpoints params
func (o *RouteDeleteContactpointsParams) WithContext(ctx context.Context) *RouteDeleteContactpointsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the route delete contactpoints params
func (o *RouteDeleteContactpointsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the route delete contactpoints params
func (o *RouteDeleteContactpointsParams) WithHTTPClient(client *http.Client) *RouteDeleteContactpointsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the route delete contactpoints params
func (o *RouteDeleteContactpointsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUID adds the uid to the route delete contactpoints params
func (o *RouteDeleteContactpointsParams) WithUID(uid string) *RouteDeleteContactpointsParams {
	o.SetUID(uid)
	return o
}

// SetUID adds the uid to the route delete contactpoints params
func (o *RouteDeleteContactpointsParams) SetUID(uid string) {
	o.UID = uid
}

// WriteToRequest writes these params to a swagger request
func (o *RouteDeleteContactpointsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param UID
	if err := r.SetPathParam("UID", o.UID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
