// Code generated by go-swagger; DO NOT EDIT.

package provisioning

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRouteGetAlertRuleGroupParams creates a new RouteGetAlertRuleGroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRouteGetAlertRuleGroupParams() *RouteGetAlertRuleGroupParams {
	return &RouteGetAlertRuleGroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRouteGetAlertRuleGroupParamsWithTimeout creates a new RouteGetAlertRuleGroupParams object
// with the ability to set a timeout on a request.
func NewRouteGetAlertRuleGroupParamsWithTimeout(timeout time.Duration) *RouteGetAlertRuleGroupParams {
	return &RouteGetAlertRuleGroupParams{
		timeout: timeout,
	}
}

// NewRouteGetAlertRuleGroupParamsWithContext creates a new RouteGetAlertRuleGroupParams object
// with the ability to set a context for a request.
func NewRouteGetAlertRuleGroupParamsWithContext(ctx context.Context) *RouteGetAlertRuleGroupParams {
	return &RouteGetAlertRuleGroupParams{
		Context: ctx,
	}
}

// NewRouteGetAlertRuleGroupParamsWithHTTPClient creates a new RouteGetAlertRuleGroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewRouteGetAlertRuleGroupParamsWithHTTPClient(client *http.Client) *RouteGetAlertRuleGroupParams {
	return &RouteGetAlertRuleGroupParams{
		HTTPClient: client,
	}
}

/* RouteGetAlertRuleGroupParams contains all the parameters to send to the API endpoint
   for the route get alert rule group operation.

   Typically these are written to a http.Request.
*/
type RouteGetAlertRuleGroupParams struct {

	// FolderUID.
	FolderUID string

	// Group.
	Group string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the route get alert rule group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteGetAlertRuleGroupParams) WithDefaults() *RouteGetAlertRuleGroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the route get alert rule group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteGetAlertRuleGroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the route get alert rule group params
func (o *RouteGetAlertRuleGroupParams) WithTimeout(timeout time.Duration) *RouteGetAlertRuleGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the route get alert rule group params
func (o *RouteGetAlertRuleGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the route get alert rule group params
func (o *RouteGetAlertRuleGroupParams) WithContext(ctx context.Context) *RouteGetAlertRuleGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the route get alert rule group params
func (o *RouteGetAlertRuleGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the route get alert rule group params
func (o *RouteGetAlertRuleGroupParams) WithHTTPClient(client *http.Client) *RouteGetAlertRuleGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the route get alert rule group params
func (o *RouteGetAlertRuleGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFolderUID adds the folderUID to the route get alert rule group params
func (o *RouteGetAlertRuleGroupParams) WithFolderUID(folderUID string) *RouteGetAlertRuleGroupParams {
	o.SetFolderUID(folderUID)
	return o
}

// SetFolderUID adds the folderUid to the route get alert rule group params
func (o *RouteGetAlertRuleGroupParams) SetFolderUID(folderUID string) {
	o.FolderUID = folderUID
}

// WithGroup adds the group to the route get alert rule group params
func (o *RouteGetAlertRuleGroupParams) WithGroup(group string) *RouteGetAlertRuleGroupParams {
	o.SetGroup(group)
	return o
}

// SetGroup adds the group to the route get alert rule group params
func (o *RouteGetAlertRuleGroupParams) SetGroup(group string) {
	o.Group = group
}

// WriteToRequest writes these params to a swagger request
func (o *RouteGetAlertRuleGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param FolderUID
	if err := r.SetPathParam("FolderUID", o.FolderUID); err != nil {
		return err
	}

	// path param Group
	if err := r.SetPathParam("Group", o.Group); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
