// Code generated by go-swagger; DO NOT EDIT.

package provisioning

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRouteGetMuteTimingsParams creates a new RouteGetMuteTimingsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRouteGetMuteTimingsParams() *RouteGetMuteTimingsParams {
	return &RouteGetMuteTimingsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRouteGetMuteTimingsParamsWithTimeout creates a new RouteGetMuteTimingsParams object
// with the ability to set a timeout on a request.
func NewRouteGetMuteTimingsParamsWithTimeout(timeout time.Duration) *RouteGetMuteTimingsParams {
	return &RouteGetMuteTimingsParams{
		timeout: timeout,
	}
}

// NewRouteGetMuteTimingsParamsWithContext creates a new RouteGetMuteTimingsParams object
// with the ability to set a context for a request.
func NewRouteGetMuteTimingsParamsWithContext(ctx context.Context) *RouteGetMuteTimingsParams {
	return &RouteGetMuteTimingsParams{
		Context: ctx,
	}
}

// NewRouteGetMuteTimingsParamsWithHTTPClient creates a new RouteGetMuteTimingsParams object
// with the ability to set a custom HTTPClient for a request.
func NewRouteGetMuteTimingsParamsWithHTTPClient(client *http.Client) *RouteGetMuteTimingsParams {
	return &RouteGetMuteTimingsParams{
		HTTPClient: client,
	}
}

/* RouteGetMuteTimingsParams contains all the parameters to send to the API endpoint
   for the route get mute timings operation.

   Typically these are written to a http.Request.
*/
type RouteGetMuteTimingsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the route get mute timings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteGetMuteTimingsParams) WithDefaults() *RouteGetMuteTimingsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the route get mute timings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteGetMuteTimingsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the route get mute timings params
func (o *RouteGetMuteTimingsParams) WithTimeout(timeout time.Duration) *RouteGetMuteTimingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the route get mute timings params
func (o *RouteGetMuteTimingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the route get mute timings params
func (o *RouteGetMuteTimingsParams) WithContext(ctx context.Context) *RouteGetMuteTimingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the route get mute timings params
func (o *RouteGetMuteTimingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the route get mute timings params
func (o *RouteGetMuteTimingsParams) WithHTTPClient(client *http.Client) *RouteGetMuteTimingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the route get mute timings params
func (o *RouteGetMuteTimingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *RouteGetMuteTimingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
