// Code generated by go-swagger; DO NOT EDIT.

package provisioning

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-api-golang-client/goclient/models"
)

// RouteGetAlertRuleReader is a Reader for the RouteGetAlertRule structure.
type RouteGetAlertRuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RouteGetAlertRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRouteGetAlertRuleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewRouteGetAlertRuleNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRouteGetAlertRuleOK creates a RouteGetAlertRuleOK with default headers values
func NewRouteGetAlertRuleOK() *RouteGetAlertRuleOK {
	return &RouteGetAlertRuleOK{}
}

/* RouteGetAlertRuleOK describes a response with status code 200, with default header values.

ProvisionedAlertRule
*/
type RouteGetAlertRuleOK struct {
	Payload *models.ProvisionedAlertRule
}

func (o *RouteGetAlertRuleOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/alert-rules/{UID}][%d] routeGetAlertRuleOK  %+v", 200, o.Payload)
}
func (o *RouteGetAlertRuleOK) GetPayload() *models.ProvisionedAlertRule {
	return o.Payload
}

func (o *RouteGetAlertRuleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProvisionedAlertRule)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRouteGetAlertRuleNotFound creates a RouteGetAlertRuleNotFound with default headers values
func NewRouteGetAlertRuleNotFound() *RouteGetAlertRuleNotFound {
	return &RouteGetAlertRuleNotFound{}
}

/* RouteGetAlertRuleNotFound describes a response with status code 404, with default header values.

Not found.
*/
type RouteGetAlertRuleNotFound struct {
}

func (o *RouteGetAlertRuleNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/alert-rules/{UID}][%d] routeGetAlertRuleNotFound ", 404)
}

func (o *RouteGetAlertRuleNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
