// Code generated by go-swagger; DO NOT EDIT.

package user_preferences

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-api-golang-client/goclient/models"
)

// PatchUserPreferencesReader is a Reader for the PatchUserPreferences structure.
type PatchUserPreferencesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchUserPreferencesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchUserPreferencesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPatchUserPreferencesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPatchUserPreferencesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPatchUserPreferencesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPatchUserPreferencesOK creates a PatchUserPreferencesOK with default headers values
func NewPatchUserPreferencesOK() *PatchUserPreferencesOK {
	return &PatchUserPreferencesOK{}
}

/* PatchUserPreferencesOK describes a response with status code 200, with default header values.

An OKResponse is returned if the request was successful.
*/
type PatchUserPreferencesOK struct {
	Payload *models.SuccessResponseBody
}

func (o *PatchUserPreferencesOK) Error() string {
	return fmt.Sprintf("[PATCH /user/preferences][%d] patchUserPreferencesOK  %+v", 200, o.Payload)
}
func (o *PatchUserPreferencesOK) GetPayload() *models.SuccessResponseBody {
	return o.Payload
}

func (o *PatchUserPreferencesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchUserPreferencesBadRequest creates a PatchUserPreferencesBadRequest with default headers values
func NewPatchUserPreferencesBadRequest() *PatchUserPreferencesBadRequest {
	return &PatchUserPreferencesBadRequest{}
}

/* PatchUserPreferencesBadRequest describes a response with status code 400, with default header values.

BadRequestError is returned when the request is invalid and it cannot be processed.
*/
type PatchUserPreferencesBadRequest struct {
	Payload *models.ErrorResponseBody
}

func (o *PatchUserPreferencesBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /user/preferences][%d] patchUserPreferencesBadRequest  %+v", 400, o.Payload)
}
func (o *PatchUserPreferencesBadRequest) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *PatchUserPreferencesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchUserPreferencesUnauthorized creates a PatchUserPreferencesUnauthorized with default headers values
func NewPatchUserPreferencesUnauthorized() *PatchUserPreferencesUnauthorized {
	return &PatchUserPreferencesUnauthorized{}
}

/* PatchUserPreferencesUnauthorized describes a response with status code 401, with default header values.

UnauthorizedError is returned when the request is not authenticated.
*/
type PatchUserPreferencesUnauthorized struct {
	Payload *models.ErrorResponseBody
}

func (o *PatchUserPreferencesUnauthorized) Error() string {
	return fmt.Sprintf("[PATCH /user/preferences][%d] patchUserPreferencesUnauthorized  %+v", 401, o.Payload)
}
func (o *PatchUserPreferencesUnauthorized) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *PatchUserPreferencesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchUserPreferencesInternalServerError creates a PatchUserPreferencesInternalServerError with default headers values
func NewPatchUserPreferencesInternalServerError() *PatchUserPreferencesInternalServerError {
	return &PatchUserPreferencesInternalServerError{}
}

/* PatchUserPreferencesInternalServerError describes a response with status code 500, with default header values.

InternalServerError is a general error indicating something went wrong internally.
*/
type PatchUserPreferencesInternalServerError struct {
	Payload *models.ErrorResponseBody
}

func (o *PatchUserPreferencesInternalServerError) Error() string {
	return fmt.Sprintf("[PATCH /user/preferences][%d] patchUserPreferencesInternalServerError  %+v", 500, o.Payload)
}
func (o *PatchUserPreferencesInternalServerError) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *PatchUserPreferencesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
