// Code generated by go-swagger; DO NOT EDIT.

package org

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-api-golang-client/goclient/models"
)

// GetOrgUsersForCurrentOrgReader is a Reader for the GetOrgUsersForCurrentOrg structure.
type GetOrgUsersForCurrentOrgReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrgUsersForCurrentOrgReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrgUsersForCurrentOrgOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetOrgUsersForCurrentOrgUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetOrgUsersForCurrentOrgForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetOrgUsersForCurrentOrgInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetOrgUsersForCurrentOrgOK creates a GetOrgUsersForCurrentOrgOK with default headers values
func NewGetOrgUsersForCurrentOrgOK() *GetOrgUsersForCurrentOrgOK {
	return &GetOrgUsersForCurrentOrgOK{}
}

/* GetOrgUsersForCurrentOrgOK describes a response with status code 200, with default header values.

(empty)
*/
type GetOrgUsersForCurrentOrgOK struct {
	Payload []*models.OrgUserDTO
}

func (o *GetOrgUsersForCurrentOrgOK) Error() string {
	return fmt.Sprintf("[GET /org/users][%d] getOrgUsersForCurrentOrgOK  %+v", 200, o.Payload)
}
func (o *GetOrgUsersForCurrentOrgOK) GetPayload() []*models.OrgUserDTO {
	return o.Payload
}

func (o *GetOrgUsersForCurrentOrgOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrgUsersForCurrentOrgUnauthorized creates a GetOrgUsersForCurrentOrgUnauthorized with default headers values
func NewGetOrgUsersForCurrentOrgUnauthorized() *GetOrgUsersForCurrentOrgUnauthorized {
	return &GetOrgUsersForCurrentOrgUnauthorized{}
}

/* GetOrgUsersForCurrentOrgUnauthorized describes a response with status code 401, with default header values.

UnauthorizedError is returned when the request is not authenticated.
*/
type GetOrgUsersForCurrentOrgUnauthorized struct {
	Payload *models.ErrorResponseBody
}

func (o *GetOrgUsersForCurrentOrgUnauthorized) Error() string {
	return fmt.Sprintf("[GET /org/users][%d] getOrgUsersForCurrentOrgUnauthorized  %+v", 401, o.Payload)
}
func (o *GetOrgUsersForCurrentOrgUnauthorized) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *GetOrgUsersForCurrentOrgUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrgUsersForCurrentOrgForbidden creates a GetOrgUsersForCurrentOrgForbidden with default headers values
func NewGetOrgUsersForCurrentOrgForbidden() *GetOrgUsersForCurrentOrgForbidden {
	return &GetOrgUsersForCurrentOrgForbidden{}
}

/* GetOrgUsersForCurrentOrgForbidden describes a response with status code 403, with default header values.

ForbiddenError is returned if the user/token has insufficient permissions to access the requested resource.
*/
type GetOrgUsersForCurrentOrgForbidden struct {
	Payload *models.ErrorResponseBody
}

func (o *GetOrgUsersForCurrentOrgForbidden) Error() string {
	return fmt.Sprintf("[GET /org/users][%d] getOrgUsersForCurrentOrgForbidden  %+v", 403, o.Payload)
}
func (o *GetOrgUsersForCurrentOrgForbidden) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *GetOrgUsersForCurrentOrgForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrgUsersForCurrentOrgInternalServerError creates a GetOrgUsersForCurrentOrgInternalServerError with default headers values
func NewGetOrgUsersForCurrentOrgInternalServerError() *GetOrgUsersForCurrentOrgInternalServerError {
	return &GetOrgUsersForCurrentOrgInternalServerError{}
}

/* GetOrgUsersForCurrentOrgInternalServerError describes a response with status code 500, with default header values.

InternalServerError is a general error indicating something went wrong internally.
*/
type GetOrgUsersForCurrentOrgInternalServerError struct {
	Payload *models.ErrorResponseBody
}

func (o *GetOrgUsersForCurrentOrgInternalServerError) Error() string {
	return fmt.Sprintf("[GET /org/users][%d] getOrgUsersForCurrentOrgInternalServerError  %+v", 500, o.Payload)
}
func (o *GetOrgUsersForCurrentOrgInternalServerError) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *GetOrgUsersForCurrentOrgInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
