// Code generated by go-swagger; DO NOT EDIT.

package dashboard_permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-api-golang-client/goclient/models"
)

// UpdateDashboardPermissionsByUIDReader is a Reader for the UpdateDashboardPermissionsByUID structure.
type UpdateDashboardPermissionsByUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateDashboardPermissionsByUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateDashboardPermissionsByUIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateDashboardPermissionsByUIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUpdateDashboardPermissionsByUIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateDashboardPermissionsByUIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateDashboardPermissionsByUIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateDashboardPermissionsByUIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateDashboardPermissionsByUIDOK creates a UpdateDashboardPermissionsByUIDOK with default headers values
func NewUpdateDashboardPermissionsByUIDOK() *UpdateDashboardPermissionsByUIDOK {
	return &UpdateDashboardPermissionsByUIDOK{}
}

/* UpdateDashboardPermissionsByUIDOK describes a response with status code 200, with default header values.

An OKResponse is returned if the request was successful.
*/
type UpdateDashboardPermissionsByUIDOK struct {
	Payload *models.SuccessResponseBody
}

func (o *UpdateDashboardPermissionsByUIDOK) Error() string {
	return fmt.Sprintf("[POST /dashboards/uid/{uid}/permissions][%d] updateDashboardPermissionsByUidOK  %+v", 200, o.Payload)
}
func (o *UpdateDashboardPermissionsByUIDOK) GetPayload() *models.SuccessResponseBody {
	return o.Payload
}

func (o *UpdateDashboardPermissionsByUIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateDashboardPermissionsByUIDBadRequest creates a UpdateDashboardPermissionsByUIDBadRequest with default headers values
func NewUpdateDashboardPermissionsByUIDBadRequest() *UpdateDashboardPermissionsByUIDBadRequest {
	return &UpdateDashboardPermissionsByUIDBadRequest{}
}

/* UpdateDashboardPermissionsByUIDBadRequest describes a response with status code 400, with default header values.

BadRequestError is returned when the request is invalid and it cannot be processed.
*/
type UpdateDashboardPermissionsByUIDBadRequest struct {
	Payload *models.ErrorResponseBody
}

func (o *UpdateDashboardPermissionsByUIDBadRequest) Error() string {
	return fmt.Sprintf("[POST /dashboards/uid/{uid}/permissions][%d] updateDashboardPermissionsByUidBadRequest  %+v", 400, o.Payload)
}
func (o *UpdateDashboardPermissionsByUIDBadRequest) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *UpdateDashboardPermissionsByUIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateDashboardPermissionsByUIDUnauthorized creates a UpdateDashboardPermissionsByUIDUnauthorized with default headers values
func NewUpdateDashboardPermissionsByUIDUnauthorized() *UpdateDashboardPermissionsByUIDUnauthorized {
	return &UpdateDashboardPermissionsByUIDUnauthorized{}
}

/* UpdateDashboardPermissionsByUIDUnauthorized describes a response with status code 401, with default header values.

UnauthorizedError is returned when the request is not authenticated.
*/
type UpdateDashboardPermissionsByUIDUnauthorized struct {
	Payload *models.ErrorResponseBody
}

func (o *UpdateDashboardPermissionsByUIDUnauthorized) Error() string {
	return fmt.Sprintf("[POST /dashboards/uid/{uid}/permissions][%d] updateDashboardPermissionsByUidUnauthorized  %+v", 401, o.Payload)
}
func (o *UpdateDashboardPermissionsByUIDUnauthorized) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *UpdateDashboardPermissionsByUIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateDashboardPermissionsByUIDForbidden creates a UpdateDashboardPermissionsByUIDForbidden with default headers values
func NewUpdateDashboardPermissionsByUIDForbidden() *UpdateDashboardPermissionsByUIDForbidden {
	return &UpdateDashboardPermissionsByUIDForbidden{}
}

/* UpdateDashboardPermissionsByUIDForbidden describes a response with status code 403, with default header values.

ForbiddenError is returned if the user/token has insufficient permissions to access the requested resource.
*/
type UpdateDashboardPermissionsByUIDForbidden struct {
	Payload *models.ErrorResponseBody
}

func (o *UpdateDashboardPermissionsByUIDForbidden) Error() string {
	return fmt.Sprintf("[POST /dashboards/uid/{uid}/permissions][%d] updateDashboardPermissionsByUidForbidden  %+v", 403, o.Payload)
}
func (o *UpdateDashboardPermissionsByUIDForbidden) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *UpdateDashboardPermissionsByUIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateDashboardPermissionsByUIDNotFound creates a UpdateDashboardPermissionsByUIDNotFound with default headers values
func NewUpdateDashboardPermissionsByUIDNotFound() *UpdateDashboardPermissionsByUIDNotFound {
	return &UpdateDashboardPermissionsByUIDNotFound{}
}

/* UpdateDashboardPermissionsByUIDNotFound describes a response with status code 404, with default header values.

NotFoundError is returned when the requested resource was not found.
*/
type UpdateDashboardPermissionsByUIDNotFound struct {
	Payload *models.ErrorResponseBody
}

func (o *UpdateDashboardPermissionsByUIDNotFound) Error() string {
	return fmt.Sprintf("[POST /dashboards/uid/{uid}/permissions][%d] updateDashboardPermissionsByUidNotFound  %+v", 404, o.Payload)
}
func (o *UpdateDashboardPermissionsByUIDNotFound) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *UpdateDashboardPermissionsByUIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateDashboardPermissionsByUIDInternalServerError creates a UpdateDashboardPermissionsByUIDInternalServerError with default headers values
func NewUpdateDashboardPermissionsByUIDInternalServerError() *UpdateDashboardPermissionsByUIDInternalServerError {
	return &UpdateDashboardPermissionsByUIDInternalServerError{}
}

/* UpdateDashboardPermissionsByUIDInternalServerError describes a response with status code 500, with default header values.

InternalServerError is a general error indicating something went wrong internally.
*/
type UpdateDashboardPermissionsByUIDInternalServerError struct {
	Payload *models.ErrorResponseBody
}

func (o *UpdateDashboardPermissionsByUIDInternalServerError) Error() string {
	return fmt.Sprintf("[POST /dashboards/uid/{uid}/permissions][%d] updateDashboardPermissionsByUidInternalServerError  %+v", 500, o.Payload)
}
func (o *UpdateDashboardPermissionsByUIDInternalServerError) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *UpdateDashboardPermissionsByUIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
