/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * API version: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package goclient

type InlineResponse2006Model struct {
	Datasource *DataSourceModel `json:"datasource"`
	// ID Identifier of the new data source.
	Id int64 `json:"id"`
	// Message Message of the deleted dashboard.
	Message string `json:"message"`
	// Name of the new data source.
	Name string `json:"name"`
}
