/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * API version: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package goclient

import (
	"time"
)

type GettableStatusModel struct {
	Cluster *ClusterStatusModel             `json:"cluster"`
	Config  *PostableApiAlertingConfigModel `json:"config"`
	// uptime
	Uptime      time.Time         `json:"uptime"`
	VersionInfo *VersionInfoModel `json:"versionInfo"`
}
