/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * API version: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package goclient

// A Route is a node that contains definitions of how to handle alerts. This is modified from the upstream alertmanager in that it adds the ObjectMatchers property.
type RouteModel struct {
	Continue_     bool           `json:"continue,omitempty"`
	GroupBy       []string       `json:"group_by,omitempty"`
	GroupInterval *DurationModel `json:"group_interval,omitempty"`
	GroupWait     *DurationModel `json:"group_wait,omitempty"`
	// Deprecated. Remove before v1.0 release.
	Match             map[string]string    `json:"match,omitempty"`
	MatchRe           *MatchRegexpsModel   `json:"match_re,omitempty"`
	Matchers          *MatchersModel       `json:"matchers,omitempty"`
	MuteTimeIntervals []string             `json:"mute_time_intervals,omitempty"`
	ObjectMatchers    *ObjectMatchersModel `json:"object_matchers,omitempty"`
	Receiver          string               `json:"receiver,omitempty"`
	RepeatInterval    *DurationModel       `json:"repeat_interval,omitempty"`
	Routes            []RouteModel         `json:"routes,omitempty"`
}
