// Code generated by go-swagger; DO NOT EDIT.

package recording_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-api-golang-client/goclient/models"
)

// DeleteRecordingRuleReader is a Reader for the DeleteRecordingRule structure.
type DeleteRecordingRuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRecordingRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteRecordingRuleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteRecordingRuleUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteRecordingRuleForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteRecordingRuleNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteRecordingRuleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteRecordingRuleOK creates a DeleteRecordingRuleOK with default headers values
func NewDeleteRecordingRuleOK() *DeleteRecordingRuleOK {
	return &DeleteRecordingRuleOK{}
}

/* DeleteRecordingRuleOK describes a response with status code 200, with default header values.

An OKResponse is returned if the request was successful.
*/
type DeleteRecordingRuleOK struct {
	Payload *models.SuccessResponseBody
}

func (o *DeleteRecordingRuleOK) Error() string {
	return fmt.Sprintf("[DELETE /recording-rules/{recordingRuleID}][%d] deleteRecordingRuleOK  %+v", 200, o.Payload)
}
func (o *DeleteRecordingRuleOK) GetPayload() *models.SuccessResponseBody {
	return o.Payload
}

func (o *DeleteRecordingRuleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRecordingRuleUnauthorized creates a DeleteRecordingRuleUnauthorized with default headers values
func NewDeleteRecordingRuleUnauthorized() *DeleteRecordingRuleUnauthorized {
	return &DeleteRecordingRuleUnauthorized{}
}

/* DeleteRecordingRuleUnauthorized describes a response with status code 401, with default header values.

UnauthorizedError is returned when the request is not authenticated.
*/
type DeleteRecordingRuleUnauthorized struct {
	Payload *models.ErrorResponseBody
}

func (o *DeleteRecordingRuleUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /recording-rules/{recordingRuleID}][%d] deleteRecordingRuleUnauthorized  %+v", 401, o.Payload)
}
func (o *DeleteRecordingRuleUnauthorized) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *DeleteRecordingRuleUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRecordingRuleForbidden creates a DeleteRecordingRuleForbidden with default headers values
func NewDeleteRecordingRuleForbidden() *DeleteRecordingRuleForbidden {
	return &DeleteRecordingRuleForbidden{}
}

/* DeleteRecordingRuleForbidden describes a response with status code 403, with default header values.

ForbiddenError is returned if the user/token has insufficient permissions to access the requested resource.
*/
type DeleteRecordingRuleForbidden struct {
	Payload *models.ErrorResponseBody
}

func (o *DeleteRecordingRuleForbidden) Error() string {
	return fmt.Sprintf("[DELETE /recording-rules/{recordingRuleID}][%d] deleteRecordingRuleForbidden  %+v", 403, o.Payload)
}
func (o *DeleteRecordingRuleForbidden) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *DeleteRecordingRuleForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRecordingRuleNotFound creates a DeleteRecordingRuleNotFound with default headers values
func NewDeleteRecordingRuleNotFound() *DeleteRecordingRuleNotFound {
	return &DeleteRecordingRuleNotFound{}
}

/* DeleteRecordingRuleNotFound describes a response with status code 404, with default header values.

NotFoundError is returned when the requested resource was not found.
*/
type DeleteRecordingRuleNotFound struct {
	Payload *models.ErrorResponseBody
}

func (o *DeleteRecordingRuleNotFound) Error() string {
	return fmt.Sprintf("[DELETE /recording-rules/{recordingRuleID}][%d] deleteRecordingRuleNotFound  %+v", 404, o.Payload)
}
func (o *DeleteRecordingRuleNotFound) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *DeleteRecordingRuleNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRecordingRuleInternalServerError creates a DeleteRecordingRuleInternalServerError with default headers values
func NewDeleteRecordingRuleInternalServerError() *DeleteRecordingRuleInternalServerError {
	return &DeleteRecordingRuleInternalServerError{}
}

/* DeleteRecordingRuleInternalServerError describes a response with status code 500, with default header values.

InternalServerError is a general error indicating something went wrong internally.
*/
type DeleteRecordingRuleInternalServerError struct {
	Payload *models.ErrorResponseBody
}

func (o *DeleteRecordingRuleInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /recording-rules/{recordingRuleID}][%d] deleteRecordingRuleInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteRecordingRuleInternalServerError) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *DeleteRecordingRuleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
