// Code generated by go-swagger; DO NOT EDIT.

package access_control

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-api-golang-client/goclient/models"
)

// NewAddBuiltinRoleParams creates a new AddBuiltinRoleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddBuiltinRoleParams() *AddBuiltinRoleParams {
	return &AddBuiltinRoleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddBuiltinRoleParamsWithTimeout creates a new AddBuiltinRoleParams object
// with the ability to set a timeout on a request.
func NewAddBuiltinRoleParamsWithTimeout(timeout time.Duration) *AddBuiltinRoleParams {
	return &AddBuiltinRoleParams{
		timeout: timeout,
	}
}

// NewAddBuiltinRoleParamsWithContext creates a new AddBuiltinRoleParams object
// with the ability to set a context for a request.
func NewAddBuiltinRoleParamsWithContext(ctx context.Context) *AddBuiltinRoleParams {
	return &AddBuiltinRoleParams{
		Context: ctx,
	}
}

// NewAddBuiltinRoleParamsWithHTTPClient creates a new AddBuiltinRoleParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddBuiltinRoleParamsWithHTTPClient(client *http.Client) *AddBuiltinRoleParams {
	return &AddBuiltinRoleParams{
		HTTPClient: client,
	}
}

/* AddBuiltinRoleParams contains all the parameters to send to the API endpoint
   for the add builtin role operation.

   Typically these are written to a http.Request.
*/
type AddBuiltinRoleParams struct {

	// Body.
	Body *models.AddBuiltInRoleCommand

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add builtin role params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddBuiltinRoleParams) WithDefaults() *AddBuiltinRoleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add builtin role params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddBuiltinRoleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add builtin role params
func (o *AddBuiltinRoleParams) WithTimeout(timeout time.Duration) *AddBuiltinRoleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add builtin role params
func (o *AddBuiltinRoleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add builtin role params
func (o *AddBuiltinRoleParams) WithContext(ctx context.Context) *AddBuiltinRoleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add builtin role params
func (o *AddBuiltinRoleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add builtin role params
func (o *AddBuiltinRoleParams) WithHTTPClient(client *http.Client) *AddBuiltinRoleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add builtin role params
func (o *AddBuiltinRoleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add builtin role params
func (o *AddBuiltinRoleParams) WithBody(body *models.AddBuiltInRoleCommand) *AddBuiltinRoleParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add builtin role params
func (o *AddBuiltinRoleParams) SetBody(body *models.AddBuiltInRoleCommand) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AddBuiltinRoleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
