// Code generated by go-swagger; DO NOT EDIT.

package access_control

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-api-golang-client/goclient/models"
)

// ListBuiltinRolesReader is a Reader for the ListBuiltinRoles structure.
type ListBuiltinRolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListBuiltinRolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListBuiltinRolesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewListBuiltinRolesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListBuiltinRolesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListBuiltinRolesOK creates a ListBuiltinRolesOK with default headers values
func NewListBuiltinRolesOK() *ListBuiltinRolesOK {
	return &ListBuiltinRolesOK{}
}

/* ListBuiltinRolesOK describes a response with status code 200, with default header values.

(empty)
*/
type ListBuiltinRolesOK struct {
	Payload map[string][]models.RoleDTO
}

func (o *ListBuiltinRolesOK) Error() string {
	return fmt.Sprintf("[GET /access-control/builtin-roles][%d] listBuiltinRolesOK  %+v", 200, o.Payload)
}
func (o *ListBuiltinRolesOK) GetPayload() map[string][]models.RoleDTO {
	return o.Payload
}

func (o *ListBuiltinRolesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListBuiltinRolesForbidden creates a ListBuiltinRolesForbidden with default headers values
func NewListBuiltinRolesForbidden() *ListBuiltinRolesForbidden {
	return &ListBuiltinRolesForbidden{}
}

/* ListBuiltinRolesForbidden describes a response with status code 403, with default header values.

ForbiddenError is returned if the user/token has insufficient permissions to access the requested resource.
*/
type ListBuiltinRolesForbidden struct {
	Payload *models.ErrorResponseBody
}

func (o *ListBuiltinRolesForbidden) Error() string {
	return fmt.Sprintf("[GET /access-control/builtin-roles][%d] listBuiltinRolesForbidden  %+v", 403, o.Payload)
}
func (o *ListBuiltinRolesForbidden) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *ListBuiltinRolesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListBuiltinRolesInternalServerError creates a ListBuiltinRolesInternalServerError with default headers values
func NewListBuiltinRolesInternalServerError() *ListBuiltinRolesInternalServerError {
	return &ListBuiltinRolesInternalServerError{}
}

/* ListBuiltinRolesInternalServerError describes a response with status code 500, with default header values.

InternalServerError is a general error indicating something went wrong internally.
*/
type ListBuiltinRolesInternalServerError struct {
	Payload *models.ErrorResponseBody
}

func (o *ListBuiltinRolesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /access-control/builtin-roles][%d] listBuiltinRolesInternalServerError  %+v", 500, o.Payload)
}
func (o *ListBuiltinRolesInternalServerError) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *ListBuiltinRolesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
