// Code generated by go-swagger; DO NOT EDIT.

package datasources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-api-golang-client/goclient/models"
)

// CheckDatasourceHealthByIDReader is a Reader for the CheckDatasourceHealthByID structure.
type CheckDatasourceHealthByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CheckDatasourceHealthByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCheckDatasourceHealthByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCheckDatasourceHealthByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCheckDatasourceHealthByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCheckDatasourceHealthByIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCheckDatasourceHealthByIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCheckDatasourceHealthByIDOK creates a CheckDatasourceHealthByIDOK with default headers values
func NewCheckDatasourceHealthByIDOK() *CheckDatasourceHealthByIDOK {
	return &CheckDatasourceHealthByIDOK{}
}

/* CheckDatasourceHealthByIDOK describes a response with status code 200, with default header values.

An OKResponse is returned if the request was successful.
*/
type CheckDatasourceHealthByIDOK struct {
	Payload *models.SuccessResponseBody
}

func (o *CheckDatasourceHealthByIDOK) Error() string {
	return fmt.Sprintf("[GET /datasources/{id}/health][%d] checkDatasourceHealthByIdOK  %+v", 200, o.Payload)
}
func (o *CheckDatasourceHealthByIDOK) GetPayload() *models.SuccessResponseBody {
	return o.Payload
}

func (o *CheckDatasourceHealthByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCheckDatasourceHealthByIDBadRequest creates a CheckDatasourceHealthByIDBadRequest with default headers values
func NewCheckDatasourceHealthByIDBadRequest() *CheckDatasourceHealthByIDBadRequest {
	return &CheckDatasourceHealthByIDBadRequest{}
}

/* CheckDatasourceHealthByIDBadRequest describes a response with status code 400, with default header values.

BadRequestError is returned when the request is invalid and it cannot be processed.
*/
type CheckDatasourceHealthByIDBadRequest struct {
	Payload *models.ErrorResponseBody
}

func (o *CheckDatasourceHealthByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /datasources/{id}/health][%d] checkDatasourceHealthByIdBadRequest  %+v", 400, o.Payload)
}
func (o *CheckDatasourceHealthByIDBadRequest) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *CheckDatasourceHealthByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCheckDatasourceHealthByIDUnauthorized creates a CheckDatasourceHealthByIDUnauthorized with default headers values
func NewCheckDatasourceHealthByIDUnauthorized() *CheckDatasourceHealthByIDUnauthorized {
	return &CheckDatasourceHealthByIDUnauthorized{}
}

/* CheckDatasourceHealthByIDUnauthorized describes a response with status code 401, with default header values.

UnauthorizedError is returned when the request is not authenticated.
*/
type CheckDatasourceHealthByIDUnauthorized struct {
	Payload *models.ErrorResponseBody
}

func (o *CheckDatasourceHealthByIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /datasources/{id}/health][%d] checkDatasourceHealthByIdUnauthorized  %+v", 401, o.Payload)
}
func (o *CheckDatasourceHealthByIDUnauthorized) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *CheckDatasourceHealthByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCheckDatasourceHealthByIDForbidden creates a CheckDatasourceHealthByIDForbidden with default headers values
func NewCheckDatasourceHealthByIDForbidden() *CheckDatasourceHealthByIDForbidden {
	return &CheckDatasourceHealthByIDForbidden{}
}

/* CheckDatasourceHealthByIDForbidden describes a response with status code 403, with default header values.

ForbiddenError is returned if the user/token has insufficient permissions to access the requested resource.
*/
type CheckDatasourceHealthByIDForbidden struct {
	Payload *models.ErrorResponseBody
}

func (o *CheckDatasourceHealthByIDForbidden) Error() string {
	return fmt.Sprintf("[GET /datasources/{id}/health][%d] checkDatasourceHealthByIdForbidden  %+v", 403, o.Payload)
}
func (o *CheckDatasourceHealthByIDForbidden) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *CheckDatasourceHealthByIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCheckDatasourceHealthByIDInternalServerError creates a CheckDatasourceHealthByIDInternalServerError with default headers values
func NewCheckDatasourceHealthByIDInternalServerError() *CheckDatasourceHealthByIDInternalServerError {
	return &CheckDatasourceHealthByIDInternalServerError{}
}

/* CheckDatasourceHealthByIDInternalServerError describes a response with status code 500, with default header values.

InternalServerError is a general error indicating something went wrong internally.
*/
type CheckDatasourceHealthByIDInternalServerError struct {
	Payload *models.ErrorResponseBody
}

func (o *CheckDatasourceHealthByIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /datasources/{id}/health][%d] checkDatasourceHealthByIdInternalServerError  %+v", 500, o.Payload)
}
func (o *CheckDatasourceHealthByIDInternalServerError) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *CheckDatasourceHealthByIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
